import React from 'react'
import img from './image/pasted image 0.png'

const Home = () => {
    return (
        <div>
            <h4>
                1. Алгоритмическая задача
            </h4>
            <p>
                Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 3 and 4, the first 10 terms of the Fibonacci-like sequence will be: 3, 4, 7, 11, 18, 29, 47, 76, 123, 199, ... . By considering the terms in this sequence whose values do not exceed seven million, find the sum of the even-valued terms.
            </p>

            <br />
            <h4>
                2. Реализовать приложение, считающее количество кликов
            </h4>

            <img src={img} alt="img"/>

            <p>
                Нужно написать приложение на React.js & TypeScript.

                Приложение имеет кнопку Кликнуть и умеет отправлять количество кликов на сервер.
                Пользователь n-раз нажимает на кнопку, запрос не отправляется, пока не пройдёт 1 секунда с момента последнего нажатия.
                Механизм отправки запроса реализовать через custom hook (без использования Redux и подобных).
                Во время ожидания ответа от сервера кнопку необходимо заблокировать и показать загрузку.
                Ответ от сервера изобразить отдельным компонентом.
                Учесть, что от сервера может прийти ошибка.
                использование библиотеки mui приветствуется.
                Решение принимается в виде репозитория на GitHub

                Для удобства мы реализовали api: lk.zont-online.ru/api/button_count. Передать количество нажатий нужно в json: '{'count: 100'}', ответ тоже будет содержать '{'count: 100'}'. В каждом запросе должен быть указан заголовок X-ZONT-Client. Укажите в этом заголовке ваш e-mail или иной контакт, по которому мы сможем связаться с вами в случае планируемых изменений в API.

                Ссылка на наш API: https://zont-online.ru/api/docs/#3394112aa9
            </p>

        </div>
    )
}

export default Home